# Site settings
title: Mage of Spades
description: Mage of Spades is Jason Blount; your personal Magento expert
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jason Blount
user_title: Your personal Magento expert
email: jasondblount@gmail.com

logo: assets/images/logo.png
favicon: assets/images/mos_logo.png

certification_url: https://u.magento.com/certification/directory/dev/id/1696332
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/jasonblount/
github_url: https://github.com/jblount12
pinterest_url:
slack_url:
dribbble_url:

# Google-analytics
google-analytics:
  id: "UA-160707509-1"

exclude: ['package.json', 'src' , 'node_modules']
